config/routes.rb
Rails.application.routes.draw do

  # users rotues
  devise_for :users, :controllers => {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  #workout routes
  resources :workouts do
    collection do
      get 'search'
    end
    member do
      get 'like'
      post 'like'
      post 'review'
      delete 'review', to: "recipes#deletereview"
    end
    resources :reviews, except: [:show, :index]
  end
  

  #page routes
  root 'pages#home'
  get 'dashboard/index'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/faq', to: 'pages#faq'

  #recipe routes
  resources :recipes do
    collection do
      get 'search'
    end
    member do
      get 'like'
      post 'like'
      post 'review'
      delete 'review', to: "recipes#deletereview"
    end
    resources :reviews, except: [:show, :index]
  end
  
  #exercises routes
  resource :dashboard, only: [:index] do
    collection do
      post :search, to: 'dashboard#search'
    end
  end
    resources :users do #might be relatable to comment
      resources :exercises 
      resources :bodyweights
  end
  #resources
  resources :calories, only: [:new, :create, :show]
  resources :feeds, only: [:new, :create, :show]
  resources :preptimes, only: [:new, :create, :show]
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  resources :dashboard, only: [:index, :search]
  resources :friendships, only: [:show, :create, :destroy]
  
   # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

    # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  
  has_many :movements
  has_many :reps
  has_many :zets
  has_many :weights  
  has_many :reviews
  has_many :likes
  has_many :comments, as: :commentable
  
  accepts_nested_attributes_for :movements,
  															reject_if: proc { |attributes| attributes['name'].blank? },
  															allow_destroy: true
 	accepts_nested_attributes_for :reps,
  															reject_if: proc { |attributes| attributes['amount'].blank? },
  															allow_destroy: true
  accepts_nested_attributes_for :zets,
  															reject_if: proc { |attributes| attributes['quantity'].blank? },
  															allow_destroy: true
 	accepts_nested_attributes_for :weights,
  															reject_if: proc { |attributes| attributes['kilogram'].blank? },
  															allow_destroy: true
  															
  validates :name, presence: true
  validates :summary, presence: true

  def thumbs_up_total
     self.likes.where(like: true).size 
  end
  
  def thumbs_down_total
      self.likes.where(like: false).size
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:edit, :update, :show, :like, :review, :destroy]
  before_action :authenticate_user!, except: [:show,  :like, :search]
  before_action :require_same_user, only: [:edit, :update]
  # before_action :admin_user, only: :destroy
  set_tab :workouts
  
  def index
    @workouts = Workout.paginate(page: params[:page], per_page: 5)
  end
  
  def show
    @random_workout = Workout.where.not(id: @workout).order("RANDOM()").first(3)
    @athletes = User.paginate(:page => params[:page])
  end
  
  def new
    @workout = Workout.new
  end
  
  def create
    @workout = Workout.new(workout_params)
    @workout.user_id = current_user.id
    
    if @workout.save
      flash[:success] = "Your workout was created successfully!"
      redirect_to workout_url(@workout)
    else
      render :new
    end
  end
  
  def review
    review = Review.create(body: params[:body], user: current_user, workout: @workout)
    if review.valid?
      flash[:success] = "Thank you for reviewing this workout"
    else
      flash[:danger] = "Review failed to post"
    end
    redirect_to :back
  end
  
  def deletereview
    Review.find(params[:revid]).destroy
    flash[:success] = "Review deleted"
    redirect_to :back
  end
  
  def edit
    
  end
  
  def update
    if @workout.update(workout_params)
      flash[:success] = "Your workout was update success"
      redirect_to workout_path(@workout)
    else
      render :edit
    end
  end
  
  def destroy
    Workout.find(params[:id]).destroy
    flash[:success] = "Workout was deleted."
    redirect_to workouts_path
  end
  
  def review
    review = Review.create(body: params[:body], user: current_user, workout: @workout)
    if review.valid?
      flash[:success] = "Thank you for reviewing this workout"
    else
      flash[:danger] = "Review failed to post"
    end
    redirect_to :back
  end
  
  def deletereview
    Review.find(params[:revid]).destroy
    flash[:success] = "Review deleted"
    redirect_to :back
  end
  
  def like 
    like = Like.create(like: params[:like], user: current_user, workout: @workout)
    if like.valid?
      flash[:success] = "Your selection was successful"
      redirect_to :back
    else
      flash[:danger] = "#{current_user.username} " + 'you can only like/dislike once per item.'
      redirect_to :back
    end
  end
  
  private
    
    def workout_params
      params.require(:workout).permit(:name, :summary, :attachment, :user_id, 
        movements_attributes: [:id, :name, :_destroy], 
        reps_attributes: [:id, :amount, :_destroy], 
        zets_attributes: [:id, :quantity, :_destroy], 
        weights_attributes: [:id, :kilogram, :_destroy],)
    end
    
    def set_workout
      @workout = Workout.find(params[:id])
    end
    
    def require_same_user
      if current_user != @workout.user and !current_user.admin?
        # flash[:danger] = "You can only edit your own recipes"
        # redirect_to recipes_path
      end
    end
  
    def admin_user
      # puts "Current user ... #{current_user.admin?}"
      # redirect_to workouts_path unless current_user.admin?
    end

end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  
  def workout_owner?
    owner_check(@workout.user_id)
  end

end

app/views/workouts/_disquis.html.erb
<div id="disqus_thread"></div>
<script>
    var disqus_config = function () {
        s.src = '//workout-app.disqus.com/embed.js';  // IMPORTANT: Replace EXAMPLE with your forum shortname!
        this.page.url = '<%= url_for(@workout) %>';
        this.page.identifier = '<%= @workout.id %>';
        this.page.title = '<%= @workout.name %>';
    };


(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//workout-app.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                

app/views/workouts/_form.html.erb
<div class="well">
  <div class='row'>
    <div class='col-md-12'>
      <%= form_for(@workout, html: { multipart: true }) do |f| %>
        <% if @workout.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@workout.errors.count, "error") %>
              prohibited this exercise from being saved: </h2>
            <ul>
              <% @workout.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :name, "Workout name" %><br>
          </div>
          <div class="col-md-10">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :summary, "Summary", placeholder: "Who's this for? what experience level? Athletes or Bodybuilders etc"  %>
          </div>
          <div class="col-md-10">
            <%= f.text_area :summary, class: "form-control", rows: 10%>
          </div>
        </div>
      <div class="clearfix">
        <div class="col-lg-4 col-md-6">
        <%= f.label :Movement %>
          <%= f.fields_for :movements do |movement| %>
            <%= render 'movement_fields', f: movement %>
        <% end %>
            <div class="links">
              <%= link_to_add_association 'Add movement', f, :movements, class: "pull-right d-inline-block btn btn-primary add-button" %>
              </br>
              </br>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
             <%= f.label :Reps %>
                <%= f.fields_for :reps do |rep| %>
                  <%= render 'rep_fields', f: rep %>
                <% end %>
            <div class="links">
              <%= link_to_add_association 'Add Reps', f, :reps, class: "pull-right d-inline-block btn btn-primary add-button" %>
            </br>
            </br>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
        <%= f.label :Sets %>
                <%= f.fields_for :zets do |zet| %>
                  <%= render 'zet_fields', f: zet %>
                <% end %>
            <div class="links">
              <%= link_to_add_association 'Add Set', f, :zets, class: "pull-right d-inline-block btn btn-primary add-button" %>
            </div>
              </br>
              </br>
        </div>
        <div>
        <strong>Upload spreadsheet: </strong>
            <span class="picture">
                <%= f.file_field :attachment %>
            </span>
        </div>
      </div>

        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit class: "btn btn-success btn-lg" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/workouts/_movement_fields.html.erb
<div class="nested-fields">
    <%= f.text_field :name %>
    <%= link_to_remove_association "Remove", f, class: "pull-left d-inline-block form-button btn btn-warning" %>
</div>

app/views/workouts/_rep_fields.html.erb
<div class="nested-fields">
    <%= f.text_field :amount %>
    <%= link_to_remove_association "Remove", f, class: "pull-left d-inline-block form-button btn btn-warning" %>
</div>

app/views/workouts/_weight_fields.html.erb
<div class="nested-fields">
    <%= f.text_field :kilogram %>
    <%= link_to_remove_association "Remove", f, class: "pull-left d-inline-block form-button btn btn-warning" %>
</div>

app/views/workouts/_zet_fields.html.erb
<div class="nested-fields">
    <%= f.text_field :quantity %>
    <%= link_to_remove_association "Remove", f, class: "pull-left d-inline-block form-button btn btn-warning" %>
</div>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<% provide(:title, "All Workout Plans") %>

<%= render "layouts/parrallax2" %>
<div class="containter">
<nav class="breadcrumb">
  <a class="breadcrumb-item" <%= link_to 'Home/', root_path%></a>
  <span class="breadcrumb-item active">Workout Plans List</span>
</nav>

<ul class="nav nav-tabs">
    <li class="active">
        <%= link_to "Workout", workouts_path %>
    </li>
    <li>
        <%= link_to "Users", users_path %>
    </li>
</ul>

<%= will_paginate %>
<% @workouts.each do |workout| %>
  <div class="row">
        <div class="col-md-2">
            <%= call_gravatar(workout.user) %>
        </div>
        <div class="col-lg-6 well">
             
             <p><%= truncate(workout.summary, length: 350) %><%= link_to 'click to see workout', workout_path(workout)%></p>
             <% if workout.attachment? %>
               <p><%= link_to "Download Workout", workout.attachment_url %></p>
             <% end %>
             <% if workout.movements.any? %>
               <p>Movements: <%= render workout.movements %></p>
             <% end %>
             <p>
                <span class='quiet'><small>Created: <%= time_ago_in_words(workout.created_at)%> ago</small></span><br>
                <span class='quiet'><small>Last edited: <%= time_ago_in_words(workout.updated_at)%> ago</small></span>
             </p>
        </div>

    </div>
    <hr>

<% end %>
</div>

<%= will_paginate %>
<%= render "layouts/carousel" %>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<% provide(:title, @workout.name.capitalize) %>


<div class="row">
    <div class="containter">
      <nav class="breadcrumb">
        <a class="breadcrumb-item" <%= link_to 'Home/', root_path%></a>
        <a class="breadcrumb-item" <%= link_to 'Workout List/', workouts_path%></a>
        <span class="breadcrumb-item active">Workout Plans</span>
      </nav>
    </div>  
    
    <%= render 'shared/page_title', title: @workout.name %>
   
    <div class="row col-md-7">
      <div class = "panel panel-success">
       <div class = "panel-heading">
          <h3 class = "panel-title"><%= @workout.name %></h3>
       </div>
       
       <div class = "panel-body">
            <p class="text-center"> <%= simple_format(@workout.summary) %></p>
          <ul class = "list-group col-xs-12 col-sm-4">
            <h4 class="list-group-item active">Exerices</h4>
            <% @workout.movements.each do |movement| %> 
              <li class = "list-group-item "><%= movement.name %></li>
            <%end%>
          </ul>
          <ul class = "list-group col-xs-12 col-sm-4">
            <h4 class="list-group-item active">Sets</h4>
            <% @workout.zets.each do |movement| %> 
              <li class = "list-group-item"><%= movement.quantity %></li>
            <%end%>
          </ul>
          <ul class = "list-group col-xs-12 col-sm-4">
            <h4 class="list-group-item active">Repetitions</h4>
            <% @workout.reps.each do |movement| %> 
              <li class = "list-group-item"><%= movement.amount %></li>
            <%end%>
          </ul>
          </br>
          <% if @workout.attachment? %>
            <%= link_to "Download Workout", @workout.attachment_url, class:'btn btn-success' %>
          <% end %>
          <div class="pull-right">
            <%= link_to like_workout_path(@workout, like: true), method: :post do %>
              <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> &nbsp <%= @workout.thumbs_up_total %>
            <% end %> &nbsp&nbsp&nbsp&nbsp
            <%= link_to like_workout_path(@workout, like: false), method: :post do %>
              <i class="fa fa-thumbs-o-down" aria-hidden="true"></i> &nbsp <%= @workout.thumbs_down_total %>
            <% end %>
          </div>
          <h5><%= link_to "Return to Workout Plan Listing", workouts_path, class: "btn btn-warning btn-small" %></h5>
        </div>
        <div class="social-share-button">
            Share this workout!<%= social_share_button_tag( "#{@workout.user.username}'s Workout Plan") %>
        </div>
          <% if logged_in? and (workout_owner? || current_user.admin?) %>
            <%= link_to "Edit this Workout", edit_workout_path(@workout), class: "btn btn-success pull-right edit" %>
           &nbsp&nbsp
            <%= link_to "[Delete Workout]", @workout, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger pull-right delete"%>
          <% end %>
      </div>
    </div>
    <div class="col-md-5 pull-right">
      <% if user?(@workout.user) %>
      	<%= render partial: 'shared/gravatar_section', locals: {user: @workout.user} %>
      <% end %>

      <hr>
      </br>
    </div>
      <div class="container reviews">
        <h3><br/>Reviews</h3>
        <% if @workout.reviews.any? %>
          <% @workout.reviews.each do |c| %>
            <div class="well">
              <div class="col-md-2 pull-right">
                <strong>User: <%= c.user.username.downcase.capitalize %> </strong>
              </div>
                <p> <%= c.body %> </p>
                <i><small><%= c.updated_at.strftime("%m/%d/%Y") %></small></i>
                <% if workout_owner? %>
                  <%= link_to "Delete Review", review_workout_path(:revid => c.id), class:"btn btn-danger btn-small pull-right", method: :delete, data: { confirm: "Are you sure you want to delete this review?" }  %>
                <% end %>
            </div>
          <% end %>
        <% else %>
          <h5>Be the first to post a review!</h5>
        <% end %>
            
        <div class="form-group">
          <%= form_tag(review_workout_path, :method=>'post') do %>
            <%= text_area_tag "body", nil, size:"5x5",  class:"form-control" %>
            <%= submit_tag "Submit Review", class: "btn btn-primary" %> <br/><br/>
        </div>
          <% end %>
        <h4><i>You may also like: </i></h4>
        <hr>
          <% @random_workout.each do |workout| %>
            <div class="row show-img">
              <%= link_to workout.name, workout %>
              <%= truncate(workout.summary, length: 150)%> <small><%=link_to 'click to see more', workout_path(workout)%></small>
            </div>
        <% end %>
  </div>
  <div class="jumbotron">
    <h1 class="display-3">Join the conversation!</h1>
    <p class="lead">Comment below and join the conversation taking place about this Workout</p>
  </div>
  <%= render 'disquis' %>
</div>