config/routes.rb
Rails.application.routes.draw do

  # users rotues
  devise_for :users, :controllers => {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  #workout routes
  resources :workouts do
    collection do
      get 'search'
    end
    member do
      get 'like'
      post 'like'
      post 'review'
      delete 'review', to: "recipes#deletereview"
    end
    resources :reviews, except: [:show, :index]
  end
  

  #page routes
  root 'pages#home'
  get 'dashboard/index'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/faq', to: 'pages#faq'

  #recipe routes
  resources :recipes do
    collection do
      get 'search'
    end
    member do
      get 'like'
      post 'like'
      post 'review'
      delete 'review', to: "recipes#deletereview"
    end
    resources :reviews, except: [:show, :index]
  end
  
  #exercises routes
  resource :dashboard, only: [:index] do
    collection do
      post :search, to: 'dashboard#search'
    end
  end
    resources :users do #might be relatable to comment
      resources :exercises 
      resources :bodyweights
  end
  #resources
  resources :calories, only: [:new, :create, :show]
  resources :feeds, only: [:new, :create, :show]
  resources :preptimes, only: [:new, :create, :show]
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  resources :dashboard, only: [:index, :search]
  resources :friendships, only: [:show, :create, :destroy]
  
   # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

    # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  
end

app/views/shared/_content_navigation.html.erb
  <%= tabs_tag :open_tabs => { :class => "nav nav-tabs" },  :active_class => "active" do |tab| %>
    <%= tab.dashboard 'Dashboard', dashboard_index_path %>
    <%= tab.workouts  'Workouts', workouts_path %>
    <%= tab.recipes   'Recipes', recipes_path %>
    <%= tab.about     'About', about_path %>
    <%= tab.faq       'FAQ', faq_url %>
    <%= tab.users     'Users', users_path %>
  <% end %>

<%= "Test: #{ensure_user}" %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="alert alert-danger col-md-8 col-md-offset-2">
            <h5>Please correct the following errors:</h5>
            <ul>
                <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end%>
            </ul>
        </div>
    </div>
<% end %>

app/views/shared/_gravatar_section.html.erb
<section class="chef_info_center">
    <p>
        <%= link_to gravatar_for(user, size: 100), user_path(user) %>
        <h5><%= link_to "#{user.first_name} (#{user.username})", user %></h5
    </p>
</section>

app/views/shared/_page_title.html.erb
<p>
    <h1><%= title %></h1>
    <hr>
</p>

<ul class="nav nav-tabs">
    <li>
        <%= link_to "Recipes", recipes_path %>
    </li>
    <li class="active">
        <%= link_to "Users", users_path %>
    </li>
</ul>