config/routes.rb
Rails.application.routes.draw do

  # users rotues
  devise_for :users, :controllers => {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  #workout routes
  resources :workouts do
    collection do
      get 'search'
    end
    member do
      get 'like'
      post 'like'
      post 'review'
      delete 'review', to: "recipes#deletereview"
    end
    resources :reviews, except: [:show, :index]
  end
  

  #page routes
  root 'pages#home'
  get 'dashboard/index'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/faq', to: 'pages#faq'

  #recipe routes
  resources :recipes do
    collection do
      get 'search'
    end
    member do
      get 'like'
      post 'like'
      post 'review'
      delete 'review', to: "recipes#deletereview"
    end
    resources :reviews, except: [:show, :index]
  end
  
  #exercises routes
  resource :dashboard, only: [:index] do
    collection do
      post :search, to: 'dashboard#search'
    end
  end
    resources :users do #might be relatable to comment
      resources :exercises 
      resources :bodyweights
  end
  #resources
  resources :calories, only: [:new, :create, :show]
  resources :feeds, only: [:new, :create, :show]
  resources :preptimes, only: [:new, :create, :show]
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  resources :dashboard, only: [:index, :search]
  resources :friendships, only: [:show, :create, :destroy]
  
   # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

    # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  
end

app/models/style.rb
class Style < ActiveRecord::Base
   validates :name, presence: true, length: {minimum: 2, maximum: 25} 
   has_many :recipe_styles
   has_many :recipes, through: :recipe_styles
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
    before_action :require_user, except: [:show]
    
    def show
       @style = Style.find(params[:id]) 
       @recipes = @style.recipes.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @style =Style.new
    end
    
    def create
       @style = Style.new(style_params)
       if @style.save
           flash[:success] = "Style was created successfully"
           redirect_to recipes_path
       else
           render 'new'
       end
    end
    
    private 
    
    def style_params
        params.require(:style).permit(:name)
    end
    
end

app/views/styles/_style.html.erb
<span class='quiet'><%= link_to style.name, style_path(style) %>, </span>

app/views/styles/new.html.erb
<%= render 'shared/page_title', title: 'Create a New Style'%>

<%= render 'shared/errors', obj: @style %>
<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @style do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
           
            <%= f.submit 'Create Style', class: "btn btn-success"%>
        <% end %>
    </div>
</div>

app/views/styles/show.html.erb
<% provide(:title, "Recipes for: #{@style.name.capitalize} food") %>

<div class="containter">
<nav class="breadcrumb">
  <a class="breadcrumb-item" <%= link_to 'Home/', root_path%></a>
  <span class="breadcrumb-item active">Styles List</span>
</nav>

<%= will_paginate @recipes %>
<% @style.recipes.each do |recipe| %>
    <div class="row">
        
        <div class="col-md-2">
            <section class="chef_info_center">
                <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
                <h5> Chef name: <%= recipe.chef.chefname %></h5>
            </section>
        </div>
        
        <div class="col-lg-6 well">
             <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
             <p><%= recipe.summary %></p>
             <p>Styles: <%= render recipe.styles %></p>
             <p>Ingredients: <%= render recipe.ingredients %></p>
             <p>
                 <span class='quiet'><small>Created: <%= time_ago_in_words(recipe.created_at)%> ago</small></span><br>
                 <span class='quiet'><small>Last edited: <%= time_ago_in_words(recipe.updated_at)%> ago</small></span>
             </p>
             <div class="pull-right">
                        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                            <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
                        <% end %> &nbsp&nbsp&nbsp&nbsp
                         <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                            <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
                        <% end %>
                    </div>
        </div>
        <div class="col-md-4">
            <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture?%>
        </div>
    </div>
    <hr>

<% end %>
</div>

<%= will_paginate @recipes%>